insert into review (id, user_id, book_id, opinion, stars, is_active) values (1, '146', '3', 'The characters were so well-developed.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (2, '120', '172', 'The characters were so well-developed.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (3, '17', '160', 'I couldn''t put it down!', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (4, '16', '121', 'It was a bit slow in the beginning', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (5, '34', '175', 'I would definitely recommend this book to others.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (6, '126', '182', 'I couldn''t put it down!', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (7, '100', '90', 'It was a bit slow in the beginning', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (8, '104', '110', 'but it picked up towards the end.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (9, '177', '62', 'I found the plot to be predictable.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (10, '161', '197', 'The characters were so well-developed.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (11, '96', '179', 'The writing style was beautiful and poetic.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (12, '190', '113', 'I found the plot to be predictable.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (13, '111', '142', 'I would definitely recommend this book to others.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (14, '172', '23', 'I loved this book!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (15, '184', '92', 'I couldn''t put it down!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (16, '28', '68', 'but it picked up towards the end.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (17, '152', '36', 'I was disappointed with the ending.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (18, '25', '131', 'This book wasn''t really my cup of tea.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (19, '131', '45', 'I was disappointed with the ending.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (20, '107', '163', 'The writing style was beautiful and poetic.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (21, '101', '9', 'The writing style was beautiful and poetic.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (22, '69', '108', 'I was disappointed with the ending.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (23, '186', '25', 'I couldn''t put it down!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (24, '15', '2', 'The writing style was beautiful and poetic.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (25, '4', '144', 'I would definitely recommend this book to others.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (26, '60', '168', 'I was disappointed with the ending.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (27, '119', '198', 'I couldn''t put it down!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (28, '142', '173', 'I loved this book!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (29, '150', '112', 'The characters were so well-developed.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (30, '27', '101', 'I found the plot to be predictable.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (31, '58', '77', 'I couldn''t put it down!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (32, '54', '189', 'I couldn''t put it down!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (33, '64', '107', 'I loved this book!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (34, '94', '70', 'I was disappointed with the ending.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (35, '62', '13', 'I would definitely recommend this book to others.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (36, '89', '75', 'I loved this book!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (37, '43', '114', 'I was disappointed with the ending.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (38, '116', '44', 'This book wasn''t really my cup of tea.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (39, '156', '153', 'I was disappointed with the ending.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (40, '147', '11', 'This book wasn''t really my cup of tea.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (41, '187', '91', 'This book wasn''t really my cup of tea.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (42, '194', '174', 'The characters were so well-developed.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (43, '73', '63', 'The characters were so well-developed.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (44, '30', '130', 'The writing style was beautiful and poetic.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (45, '114', '129', 'The writing style was beautiful and poetic.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (46, '91', '93', 'It was a bit slow in the beginning', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (47, '123', '35', 'I couldn''t put it down!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (48, '188', '27', 'It was a bit slow in the beginning', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (49, '33', '42', 'This book wasn''t really my cup of tea.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (50, '14', '188', 'but it picked up towards the end.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (51, '80', '158', 'I would definitely recommend this book to others.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (52, '66', '80', 'I loved this book!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (53, '7', '96', 'I would definitely recommend this book to others.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (54, '41', '60', 'I loved this book!', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (55, '48', '106', 'I was disappointed with the ending.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (56, '108', '171', 'It was a bit slow in the beginning', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (57, '95', '177', 'It was a bit slow in the beginning', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (58, '50', '191', 'This book wasn''t really my cup of tea.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (59, '11', '199', 'The writing style was beautiful and poetic.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (60, '192', '146', 'The writing style was beautiful and poetic.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (61, '57', '47', 'I couldn''t put it down!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (62, '53', '117', 'I couldn''t put it down!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (63, '125', '46', 'This book was a page-turner!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (64, '182', '126', 'I found the plot to be predictable.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (65, '52', '55', 'I would definitely recommend this book to others.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (66, '85', '151', 'I would definitely recommend this book to others.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (67, '169', '103', 'I found the plot to be predictable.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (68, '193', '12', 'I loved this book!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (69, '56', '56', 'The writing style was beautiful and poetic.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (70, '144', '178', 'This book wasn''t really my cup of tea.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (71, '183', '138', 'I found the plot to be predictable.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (72, '178', '73', 'I couldn''t put it down!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (73, '164', '124', 'I was disappointed with the ending.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (74, '18', '154', 'This book was a page-turner!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (75, '9', '122', 'This book wasn''t really my cup of tea.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (76, '20', '67', 'I would definitely recommend this book to others.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (77, '153', '162', 'This book wasn''t really my cup of tea.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (78, '151', '5', 'This book was a page-turner!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (79, '155', '69', 'The characters were so well-developed.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (80, '129', '100', 'I was disappointed with the ending.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (81, '154', '155', 'This book was a page-turner!', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (82, '75', '147', 'I loved this book!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (83, '82', '139', 'I would definitely recommend this book to others.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (84, '23', '94', 'This book was a page-turner!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (85, '35', '186', 'I was disappointed with the ending.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (86, '199', '71', 'This book wasn''t really my cup of tea.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (87, '122', '156', 'I found the plot to be predictable.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (88, '8', '82', 'The characters were so well-developed.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (89, '72', '169', 'I would definitely recommend this book to others.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (90, '5', '6', 'I was disappointed with the ending.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (91, '173', '21', 'I loved this book!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (92, '61', '150', 'This book wasn''t really my cup of tea.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (93, '46', '61', 'The writing style was beautiful and poetic.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (94, '21', '115', 'The characters were so well-developed.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (95, '168', '54', 'I found the plot to be predictable.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (96, '134', '57', 'This book wasn''t really my cup of tea.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (97, '1', '81', 'I found the plot to be predictable.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (98, '145', '37', 'The writing style was beautiful and poetic.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (99, '197', '200', 'This book wasn''t really my cup of tea.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (100, '200', '159', 'I couldn''t put it down!', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (101, '112', '187', 'I couldn''t put it down!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (102, '76', '14', 'but it picked up towards the end.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (103, '185', '4', 'I was disappointed with the ending.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (104, '132', '19', 'This book was a page-turner!', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (105, '81', '127', 'It was a bit slow in the beginning', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (106, '133', '166', 'I was disappointed with the ending.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (107, '65', '102', 'I was disappointed with the ending.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (108, '198', '39', 'The characters were so well-developed.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (109, '127', '72', 'It was a bit slow in the beginning', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (110, '170', '22', 'I was disappointed with the ending.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (111, '159', '180', 'I would definitely recommend this book to others.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (112, '165', '20', 'I loved this book!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (113, '148', '133', 'This book was a page-turner!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (114, '176', '195', 'It was a bit slow in the beginning', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (115, '103', '64', 'The characters were so well-developed.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (116, '10', '33', 'This book was a page-turner!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (117, '118', '123', 'I was disappointed with the ending.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (118, '84', '181', 'I would definitely recommend this book to others.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (119, '166', '149', 'I was disappointed with the ending.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (120, '136', '196', 'I was disappointed with the ending.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (121, '31', '141', 'but it picked up towards the end.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (122, '117', '99', 'but it picked up towards the end.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (123, '71', '192', 'The characters were so well-developed.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (124, '63', '98', 'It was a bit slow in the beginning', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (125, '49', '118', 'This book wasn''t really my cup of tea.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (126, '2', '125', 'This book wasn''t really my cup of tea.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (127, '113', '161', 'The characters were so well-developed.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (128, '24', '128', 'The writing style was beautiful and poetic.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (129, '90', '164', 'It was a bit slow in the beginning', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (130, '83', '165', 'The characters were so well-developed.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (131, '143', '109', 'I was disappointed with the ending.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (132, '45', '97', 'This book was a page-turner!', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (133, '42', '143', 'This book was a page-turner!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (134, '44', '74', 'I found the plot to be predictable.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (135, '19', '83', 'I couldn''t put it down!', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (136, '163', '184', 'This book was a page-turner!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (137, '59', '53', 'The characters were so well-developed.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (138, '149', '78', 'This book wasn''t really my cup of tea.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (139, '167', '34', 'I was disappointed with the ending.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (140, '97', '88', 'I couldn''t put it down!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (141, '171', '152', 'This book was a page-turner!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (142, '115', '59', 'It was a bit slow in the beginning', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (143, '109', '95', 'I found the plot to be predictable.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (144, '3', '183', 'I found the plot to be predictable.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (145, '87', '140', 'This book was a page-turner!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (146, '102', '167', 'I would definitely recommend this book to others.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (147, '106', '28', 'The writing style was beautiful and poetic.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (148, '74', '76', 'This book wasn''t really my cup of tea.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (149, '181', '157', 'This book wasn''t really my cup of tea.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (150, '158', '24', 'I would definitely recommend this book to others.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (151, '191', '79', 'I loved this book!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (152, '174', '7', 'I loved this book!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (153, '26', '84', 'I would definitely recommend this book to others.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (154, '160', '190', 'I was disappointed with the ending.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (155, '128', '51', 'The characters were so well-developed.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (156, '78', '135', 'This book was a page-turner!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (157, '79', '132', 'The writing style was beautiful and poetic.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (158, '47', '105', 'This book wasn''t really my cup of tea.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (159, '13', '176', 'I found the plot to be predictable.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (160, '38', '87', 'I found the plot to be predictable.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (161, '130', '17', 'I would definitely recommend this book to others.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (162, '55', '134', 'I couldn''t put it down!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (163, '105', '31', 'This book was a page-turner!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (164, '140', '104', 'I found the plot to be predictable.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (165, '124', '49', 'I couldn''t put it down!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (166, '88', '170', 'The characters were so well-developed.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (167, '29', '50', 'This book wasn''t really my cup of tea.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (168, '40', '1', 'The writing style was beautiful and poetic.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (169, '189', '30', 'I was disappointed with the ending.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (170, '39', '193', 'I couldn''t put it down!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (171, '51', '89', 'This book was a page-turner!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (172, '70', '8', 'I would definitely recommend this book to others.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (173, '93', '18', 'I was disappointed with the ending.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (174, '67', '16', 'I couldn''t put it down!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (175, '196', '145', 'but it picked up towards the end.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (176, '92', '185', 'This book wasn''t really my cup of tea.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (177, '180', '38', 'This book wasn''t really my cup of tea.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (178, '36', '194', 'I couldn''t put it down!', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (179, '137', '85', 'I found the plot to be predictable.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (180, '121', '116', 'The writing style was beautiful and poetic.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (181, '32', '57', 'but it picked up towards the end.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (182, '111', '35', 'It was a bit slow in the beginning', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (183, '180', '87', 'The writing style was beautiful and poetic.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (184, '87', '188', 'It was a bit slow in the beginning', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (185, '66', '70', 'but it picked up towards the end.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (186, '188', '178', 'I found the plot to be predictable.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (187, '68', '5', 'but it picked up towards the end.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (188, '13', '124', 'It was a bit slow in the beginning', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (189, '107', '44', 'I loved this book!', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (190, '40', '12', 'I couldn''t put it down!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (191, '39', '28', 'The characters were so well-developed.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (192, '55', '11', 'This book was a page-turner!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (193, '126', '32', 'I couldn''t put it down!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (194, '176', '129', 'It was a bit slow in the beginning', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (195, '84', '86', 'This book was a page-turner!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (196, '110', '81', 'It was a bit slow in the beginning', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (197, '12', '94', 'This book was a page-turner!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (198, '103', '49', 'but it picked up towards the end.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (199, '60', '66', 'but it picked up towards the end.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (200, '3', '185', 'I was disappointed with the ending.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (201, '136', '107', 'I would definitely recommend this book to others.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (202, '162', '138', 'but it picked up towards the end.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (203, '184', '63', 'This book was a page-turner!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (204, '170', '119', 'I found the plot to be predictable.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (205, '130', '109', 'I loved this book!', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (206, '85', '123', 'I loved this book!', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (207, '64', '61', 'This book wasn''t really my cup of tea.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (208, '22', '171', 'but it picked up towards the end.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (209, '23', '127', 'The writing style was beautiful and poetic.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (210, '121', '67', 'The writing style was beautiful and poetic.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (211, '106', '167', 'I was disappointed with the ending.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (212, '72', '151', 'This book was a page-turner!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (213, '45', '181', 'It was a bit slow in the beginning', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (214, '78', '24', 'It was a bit slow in the beginning', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (215, '30', '152', 'This book was a page-turner!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (216, '76', '59', 'I would definitely recommend this book to others.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (217, '174', '135', 'but it picked up towards the end.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (218, '41', '42', 'This book wasn''t really my cup of tea.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (219, '156', '96', 'I was disappointed with the ending.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (220, '98', '101', 'I loved this book!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (221, '173', '194', 'The writing style was beautiful and poetic.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (222, '112', '160', 'I was disappointed with the ending.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (223, '15', '68', 'I loved this book!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (224, '141', '166', 'The writing style was beautiful and poetic.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (225, '6', '177', 'The characters were so well-developed.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (226, '27', '176', 'I was disappointed with the ending.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (227, '36', '145', 'It was a bit slow in the beginning', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (228, '171', '93', 'I was disappointed with the ending.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (229, '62', '41', 'The writing style was beautiful and poetic.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (230, '196', '189', 'I would definitely recommend this book to others.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (231, '179', '190', 'It was a bit slow in the beginning', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (232, '117', '115', 'The characters were so well-developed.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (233, '5', '172', 'I found the plot to be predictable.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (234, '193', '146', 'I loved this book!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (235, '42', '169', 'This book was a page-turner!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (236, '118', '153', 'I found the plot to be predictable.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (237, '94', '175', 'I loved this book!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (238, '38', '72', 'I couldn''t put it down!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (239, '51', '113', 'It was a bit slow in the beginning', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (240, '127', '147', 'I was disappointed with the ending.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (241, '116', '103', 'I was disappointed with the ending.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (242, '186', '162', 'I would definitely recommend this book to others.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (243, '200', '38', 'The writing style was beautiful and poetic.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (244, '195', '58', 'The characters were so well-developed.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (245, '82', '174', 'This book wasn''t really my cup of tea.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (246, '164', '116', 'I would definitely recommend this book to others.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (247, '20', '80', 'I was disappointed with the ending.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (248, '11', '48', 'I would definitely recommend this book to others.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (249, '93', '20', 'I loved this book!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (250, '132', '52', 'I was disappointed with the ending.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (251, '90', '136', 'but it picked up towards the end.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (252, '113', '83', 'This book wasn''t really my cup of tea.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (253, '70', '108', 'I was disappointed with the ending.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (254, '119', '3', 'The characters were so well-developed.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (255, '177', '37', 'The characters were so well-developed.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (256, '102', '173', 'It was a bit slow in the beginning', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (257, '149', '128', 'I loved this book!', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (258, '80', '161', 'I found the plot to be predictable.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (259, '143', '117', 'It was a bit slow in the beginning', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (260, '44', '199', 'This book wasn''t really my cup of tea.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (261, '151', '122', 'I found the plot to be predictable.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (262, '135', '6', 'The writing style was beautiful and poetic.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (263, '31', '89', 'I found the plot to be predictable.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (264, '168', '157', 'The characters were so well-developed.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (265, '99', '126', 'The writing style was beautiful and poetic.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (266, '56', '197', 'but it picked up towards the end.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (267, '105', '140', 'I couldn''t put it down!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (268, '57', '29', 'I was disappointed with the ending.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (269, '172', '14', 'The writing style was beautiful and poetic.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (270, '10', '159', 'The writing style was beautiful and poetic.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (271, '26', '50', 'This book wasn''t really my cup of tea.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (272, '167', '30', 'I was disappointed with the ending.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (273, '165', '16', 'I found the plot to be predictable.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (274, '161', '43', 'I couldn''t put it down!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (275, '97', '78', 'I loved this book!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (276, '166', '23', 'I was disappointed with the ending.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (277, '53', '91', 'This book wasn''t really my cup of tea.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (278, '198', '51', 'I loved this book!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (279, '181', '158', 'This book wasn''t really my cup of tea.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (280, '46', '133', 'I loved this book!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (281, '69', '39', 'I was disappointed with the ending.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (282, '199', '1', 'It was a bit slow in the beginning', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (283, '108', '4', 'but it picked up towards the end.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (284, '139', '186', 'The writing style was beautiful and poetic.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (285, '61', '168', 'but it picked up towards the end.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (286, '133', '60', 'It was a bit slow in the beginning', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (287, '140', '105', 'I couldn''t put it down!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (288, '159', '98', 'I found the plot to be predictable.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (289, '131', '22', 'I found the plot to be predictable.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (290, '92', '10', 'I loved this book!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (291, '154', '45', 'I was disappointed with the ending.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (292, '153', '142', 'The writing style was beautiful and poetic.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (293, '52', '27', 'but it picked up towards the end.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (294, '74', '179', 'It was a bit slow in the beginning', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (295, '191', '69', 'The characters were so well-developed.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (296, '59', '132', 'This book wasn''t really my cup of tea.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (297, '73', '198', 'This book wasn''t really my cup of tea.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (298, '138', '130', 'This book wasn''t really my cup of tea.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (299, '32', '18', 'The writing style was beautiful and poetic.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (300, '145', '21', 'I would definitely recommend this book to others.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (301, '16', '36', 'This book was a page-turner!', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (302, '17', '165', 'I couldn''t put it down!', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (303, '88', '90', 'This book was a page-turner!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (304, '33', '187', 'This book was a page-turner!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (305, '137', '33', 'I was disappointed with the ending.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (306, '48', '15', 'I was disappointed with the ending.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (307, '71', '92', 'I was disappointed with the ending.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (308, '34', '84', 'I loved this book!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (309, '115', '25', 'I would definitely recommend this book to others.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (310, '101', '77', 'This book was a page-turner!', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (311, '89', '200', 'but it picked up towards the end.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (312, '8', '141', 'It was a bit slow in the beginning', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (313, '14', '164', 'I couldn''t put it down!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (314, '50', '183', 'It was a bit slow in the beginning', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (315, '190', '31', 'The writing style was beautiful and poetic.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (316, '19', '170', 'I would definitely recommend this book to others.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (317, '49', '2', 'but it picked up towards the end.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (318, '21', '150', 'I was disappointed with the ending.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (319, '147', '26', 'I couldn''t put it down!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (320, '189', '102', 'The characters were so well-developed.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (321, '160', '74', 'The writing style was beautiful and poetic.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (322, '175', '110', 'I couldn''t put it down!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (323, '125', '9', 'The characters were so well-developed.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (324, '54', '65', 'I would definitely recommend this book to others.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (325, '194', '121', 'I found the plot to be predictable.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (326, '182', '184', 'I found the plot to be predictable.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (327, '83', '131', 'The characters were so well-developed.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (328, '79', '85', 'It was a bit slow in the beginning', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (329, '192', '34', 'but it picked up towards the end.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (330, '9', '144', 'but it picked up towards the end.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (331, '109', '120', 'The characters were so well-developed.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (332, '155', '156', 'I couldn''t put it down!', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (333, '123', '100', 'This book wasn''t really my cup of tea.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (334, '129', '55', 'I found the plot to be predictable.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (335, '7', '139', 'This book was a page-turner!', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (336, '28', '62', 'I was disappointed with the ending.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (337, '128', '40', 'I couldn''t put it down!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (338, '163', '99', 'I would definitely recommend this book to others.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (339, '150', '53', 'but it picked up towards the end.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (340, '86', '54', 'I would definitely recommend this book to others.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (341, '75', '106', 'The writing style was beautiful and poetic.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (342, '134', '75', 'This book was a page-turner!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (343, '65', '195', 'but it picked up towards the end.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (344, '2', '76', 'It was a bit slow in the beginning', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (345, '114', '95', 'I loved this book!', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (346, '152', '73', 'The characters were so well-developed.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (347, '77', '7', 'I couldn''t put it down!', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (348, '187', '191', 'This book was a page-turner!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (349, '142', '64', 'The characters were so well-developed.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (350, '1', '193', 'but it picked up towards the end.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (351, '124', '118', 'The writing style was beautiful and poetic.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (352, '24', '19', 'This book wasn''t really my cup of tea.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (353, '100', '149', 'This book was a page-turner!', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (354, '144', '196', 'I loved this book!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (355, '25', '137', 'The writing style was beautiful and poetic.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (356, '96', '56', 'I would definitely recommend this book to others.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (357, '29', '104', 'The writing style was beautiful and poetic.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (358, '178', '112', 'The writing style was beautiful and poetic.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (359, '95', '155', 'I couldn''t put it down!', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (360, '169', '163', 'It was a bit slow in the beginning', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (361, '58', '97', 'This book wasn''t really my cup of tea.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (362, '81', '17', 'The characters were so well-developed.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (363, '91', '180', 'I would definitely recommend this book to others.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (364, '157', '8', 'The writing style was beautiful and poetic.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (365, '67', '71', 'I was disappointed with the ending.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (366, '18', '35', 'I was disappointed with the ending.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (367, '65', '128', 'I found the plot to be predictable.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (368, '108', '178', 'I would definitely recommend this book to others.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (369, '61', '19', 'I would definitely recommend this book to others.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (370, '94', '40', 'The writing style was beautiful and poetic.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (371, '155', '198', 'The writing style was beautiful and poetic.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (372, '92', '99', 'The writing style was beautiful and poetic.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (373, '66', '79', 'The writing style was beautiful and poetic.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (374, '168', '65', 'The writing style was beautiful and poetic.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (375, '58', '171', 'The characters were so well-developed.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (376, '173', '85', 'I couldn''t put it down!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (377, '110', '122', 'The writing style was beautiful and poetic.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (378, '165', '125', 'I found the plot to be predictable.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (379, '122', '192', 'I was disappointed with the ending.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (380, '5', '77', 'but it picked up towards the end.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (381, '163', '162', 'The characters were so well-developed.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (382, '107', '136', 'but it picked up towards the end.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (383, '3', '121', 'I found the plot to be predictable.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (384, '70', '100', 'This book wasn''t really my cup of tea.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (385, '148', '173', 'I loved this book!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (386, '113', '105', 'It was a bit slow in the beginning', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (387, '2', '23', 'I would definitely recommend this book to others.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (388, '50', '76', 'I loved this book!', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (389, '135', '57', 'This book wasn''t really my cup of tea.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (390, '31', '20', 'I couldn''t put it down!', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (391, '177', '160', 'I was disappointed with the ending.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (392, '139', '132', 'I couldn''t put it down!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (393, '134', '28', 'I found the plot to be predictable.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (394, '56', '16', 'I couldn''t put it down!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (395, '154', '43', 'I loved this book!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (396, '64', '119', 'This book wasn''t really my cup of tea.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (397, '164', '199', 'This book wasn''t really my cup of tea.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (398, '126', '53', 'I was disappointed with the ending.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (399, '88', '87', 'It was a bit slow in the beginning', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (400, '123', '154', 'It was a bit slow in the beginning', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (401, '49', '21', 'but it picked up towards the end.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (402, '45', '103', 'I couldn''t put it down!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (403, '194', '197', 'but it picked up towards the end.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (404, '178', '48', 'I found the plot to be predictable.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (405, '18', '151', 'This book wasn''t really my cup of tea.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (406, '19', '190', 'It was a bit slow in the beginning', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (407, '161', '80', 'but it picked up towards the end.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (408, '112', '131', 'I loved this book!', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (409, '16', '13', 'I found the plot to be predictable.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (410, '181', '54', 'I couldn''t put it down!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (411, '21', '152', 'It was a bit slow in the beginning', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (412, '116', '161', 'I couldn''t put it down!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (413, '153', '106', 'The writing style was beautiful and poetic.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (414, '93', '96', 'I loved this book!', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (415, '192', '94', 'The writing style was beautiful and poetic.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (416, '149', '73', 'It was a bit slow in the beginning', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (417, '51', '6', 'The writing style was beautiful and poetic.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (418, '9', '42', 'I would definitely recommend this book to others.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (419, '11', '167', 'but it picked up towards the end.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (420, '141', '63', 'This book wasn''t really my cup of tea.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (421, '79', '30', 'I loved this book!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (422, '138', '179', 'It was a bit slow in the beginning', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (423, '196', '191', 'I found the plot to be predictable.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (424, '172', '68', 'I found the plot to be predictable.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (425, '41', '45', 'I would definitely recommend this book to others.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (426, '119', '111', 'This book was a page-turner!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (427, '62', '5', 'I was disappointed with the ending.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (428, '186', '134', 'I was disappointed with the ending.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (429, '157', '141', 'I couldn''t put it down!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (430, '193', '159', 'The writing style was beautiful and poetic.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (431, '53', '55', 'but it picked up towards the end.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (432, '97', '81', 'This book was a page-turner!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (433, '159', '163', 'but it picked up towards the end.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (434, '83', '7', 'I couldn''t put it down!', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (435, '105', '50', 'I was disappointed with the ending.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (436, '6', '196', 'This book wasn''t really my cup of tea.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (437, '179', '155', 'I would definitely recommend this book to others.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (438, '100', '93', 'The writing style was beautiful and poetic.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (439, '43', '26', 'The writing style was beautiful and poetic.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (440, '128', '59', 'The characters were so well-developed.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (441, '76', '70', 'This book was a page-turner!', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (442, '102', '46', 'This book wasn''t really my cup of tea.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (443, '39', '112', 'I was disappointed with the ending.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (444, '143', '149', 'The writing style was beautiful and poetic.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (445, '160', '62', 'This book wasn''t really my cup of tea.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (446, '109', '107', 'I found the plot to be predictable.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (447, '47', '145', 'This book was a page-turner!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (448, '184', '187', 'I couldn''t put it down!', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (449, '129', '18', 'I couldn''t put it down!', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (450, '176', '89', 'I couldn''t put it down!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (451, '187', '9', 'It was a bit slow in the beginning', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (452, '87', '135', 'but it picked up towards the end.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (453, '68', '39', 'but it picked up towards the end.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (454, '20', '41', 'This book wasn''t really my cup of tea.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (455, '71', '140', 'The writing style was beautiful and poetic.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (456, '59', '118', 'I couldn''t put it down!', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (457, '158', '36', 'but it picked up towards the end.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (458, '152', '22', 'I would definitely recommend this book to others.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (459, '169', '78', 'I found the plot to be predictable.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (460, '125', '189', 'I loved this book!', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (461, '1', '116', 'The characters were so well-developed.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (462, '120', '156', 'The characters were so well-developed.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (463, '170', '44', 'This book was a page-turner!', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (464, '191', '90', 'It was a bit slow in the beginning', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (465, '32', '31', 'This book wasn''t really my cup of tea.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (466, '63', '82', 'but it picked up towards the end.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (467, '101', '150', 'but it picked up towards the end.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (468, '144', '124', 'The characters were so well-developed.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (469, '171', '3', 'This book wasn''t really my cup of tea.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (470, '57', '37', 'The writing style was beautiful and poetic.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (471, '167', '97', 'I was disappointed with the ending.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (472, '189', '120', 'I was disappointed with the ending.', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (473, '78', '15', 'I was disappointed with the ending.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (474, '54', '86', 'I loved this book!', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (475, '77', '153', 'The characters were so well-developed.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (476, '140', '176', 'The characters were so well-developed.', 5, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (477, '118', '61', 'I would definitely recommend this book to others.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (478, '72', '24', 'This book wasn''t really my cup of tea.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (479, '86', '98', 'It was a bit slow in the beginning', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (480, '7', '185', 'I was disappointed with the ending.', 1, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (481, '10', '142', 'I was disappointed with the ending.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (482, '147', '38', 'The writing style was beautiful and poetic.', 5, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (483, '26', '169', 'This book wasn''t really my cup of tea.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (484, '145', '51', 'I was disappointed with the ending.', 1, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (485, '82', '137', 'This book was a page-turner!', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (486, '183', '195', 'I loved this book!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (487, '137', '177', 'This book was a page-turner!', 2, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (488, '55', '14', 'I would definitely recommend this book to others.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (489, '131', '11', 'I found the plot to be predictable.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (490, '124', '66', 'The writing style was beautiful and poetic.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (491, '130', '168', 'I would definitely recommend this book to others.', 2, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (492, '15', '129', 'I would definitely recommend this book to others.', 4, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (493, '197', '143', 'The characters were so well-developed.', 4, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (494, '80', '27', 'I loved this book!', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (495, '37', '184', 'This book was a page-turner!', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (496, '175', '95', 'It was a bit slow in the beginning', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (497, '150', '200', 'I found the plot to be predictable.', 3, 0);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (498, '127', '108', 'I found the plot to be predictable.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (499, '73', '193', 'but it picked up towards the end.', 3, 1);
insert into review (id, user_id, book_id, opinion, stars, is_active) values (500, '27', '165', 'I couldn''t put it down!', 5, 0);
