insert into categories (id, category) values (1, 'Mystery');
insert into categories (id, category) values (2, 'Romance');
insert into categories (id, category) values (3, 'Science Fiction');
insert into categories (id, category) values (4, 'Fantasy');
insert into categories (id, category) values (5, 'Thriller');
insert into categories (id, category) values (6, 'Horror');
insert into categories (id, category) values (7, 'Historical Fiction');
insert into categories (id, category) values (8, 'Memoir');
insert into categories (id, category) values (9, 'Biography');
insert into categories (id, category) values (10, 'Self-Help');
