insert into keywords (id, keyword) values (1, 'mystery');
insert into keywords (id, keyword) values (2, 'romance');
insert into keywords (id, keyword) values (3, 'thriller');
insert into keywords (id, keyword) values (4, 'fantasy');
insert into keywords (id, keyword) values (5, 'sci-fi');
insert into keywords (id, keyword) values (6, 'historical fiction');
insert into keywords (id, keyword) values (7, 'self-help');
insert into keywords (id, keyword) values (8, 'biography');
insert into keywords (id, keyword) values (9, 'travel');
insert into keywords (id, keyword) values (10, 'cookbook');
